"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { Check, CircleAlert, Clock, Copy, Mail, MessageSquare, Smartphone, X } from "lucide-react";
import type { ChannelOutcome, IssuedInvitation } from "../../lib/api";
import { Button } from "../ui/button";

// The moment after an invitation is sent.
//
// The code is shown large, once, with the QR beside it, because the most common
// way this gets used in a pilot is an inspector standing at the administrator's
// desk with a new phone. For everyone else it says where the code went — by SMS,
// by email, or not at all — so the administrator knows what to tell them.

function firstName(full: string): string {
  return full.trim().split(/\s+/)[0] ?? full;
}

function expiry(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    weekday: "short",
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function Channel({ icon, label, outcome }: { icon: ReactNode; label: string; outcome: ChannelOutcome }) {
  const tone =
    outcome.status === "sent"
      ? "border-success-border bg-success-muted text-success"
      : outcome.status === "failed"
        ? "border-destructive-border bg-destructive-muted text-destructive"
        : "border-line bg-surface-sunk text-ink-muted";
  const word =
    outcome.status === "sent" ? "Sent" : outcome.status === "failed" ? "Not delivered" : "Not sent";
  return (
    <div className={`flex items-start gap-3 rounded-control border px-3 py-2.5 ${tone}`}>
      <span className="mt-0.5 shrink-0" aria-hidden>
        {icon}
      </span>
      <div className="min-w-0 text-sm">
        <p className="font-medium">
          {label} · {word}
        </p>
        <p className="truncate text-xs opacity-80" title={outcome.detail ?? undefined}>
          {outcome.to ?? outcome.detail ?? "—"}
          {/* On a failure it says why; on a demo server, that "sent" meant the
              service log rather than a real phone or inbox. */}
          {outcome.to && outcome.detail ? ` — ${outcome.detail}` : ""}
        </p>
      </div>
    </div>
  );
}

export function InviteCard({ invitation, onClose }: { invitation: IssuedInvitation; onClose: () => void }) {
  const [copied, setCopied] = useState(false);
  const nothingSent = invitation.email.status !== "sent" && invitation.sms.status !== "sent";

  async function copy() {
    try {
      await navigator.clipboard.writeText(invitation.code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* the code is on screen either way */
    }
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.08em] text-success">Invite ready</p>
          <h2 className="mt-1 text-xl font-semibold tracking-tight text-ink">
            {firstName(invitation.fullName)} can set up their phone
          </h2>
          <p className="mt-1 text-sm text-ink-muted">
            They open the AgroAssure app and enter this code. Nobody needs to approve anything after.
          </p>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="rounded-control p-1.5 text-ink-faint transition-colors hover:bg-surface-sunk hover:text-ink"
          aria-label="Close"
        >
          <X className="size-5" />
        </button>
      </div>

      <div className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-center">
        <div className="rounded-card border border-primary-100 bg-primary-50 px-5 py-4 text-center">
          <p className="text-[0.6875rem] font-semibold uppercase tracking-[0.1em] text-ink-muted">Invite code</p>
          <p className="mt-1 font-mono text-3xl font-semibold tracking-[0.14em] text-ink sm:text-4xl" aria-live="polite">
            {invitation.code}
          </p>
          <button
            type="button"
            onClick={copy}
            className="mt-3 inline-flex items-center gap-1.5 rounded-pill bg-card px-3 py-1 text-xs font-medium text-primary-700 ring-1 ring-inset ring-primary-200 transition-colors hover:bg-primary-100"
          >
            {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
            {copied ? "Copied" : "Copy code"}
          </button>
        </div>
        <figure className="mx-auto flex flex-col items-center gap-1.5">
          <div
            className="size-36 overflow-hidden rounded-control border border-line bg-white p-1.5 [&_svg]:h-full [&_svg]:w-full"
            // Generated by the gateway's QR encoder from the activation link;
            // it contains no text from the form.
            dangerouslySetInnerHTML={{ __html: invitation.qrSvg }}
          />
          <figcaption className="flex items-center gap-1 text-xs text-ink-muted">
            <Smartphone className="size-3.5" aria-hidden /> Scan with their phone
          </figcaption>
        </figure>
      </div>

      <div className="grid gap-2 sm:grid-cols-2">
        <Channel icon={<MessageSquare className="size-4" />} label="SMS" outcome={invitation.sms} />
        <Channel icon={<Mail className="size-4" />} label="Email" outcome={invitation.email} />
      </div>

      {nothingSent ? (
        <p className="flex items-start gap-2 rounded-control border border-warning-border bg-warning-muted px-3 py-2.5 text-sm text-warning">
          <CircleAlert className="mt-0.5 size-4 shrink-0" aria-hidden />
          The code didn&rsquo;t go out automatically. Read it to them, or let them scan the QR code.
        </p>
      ) : null}

      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4">
        <p className="flex items-center gap-1.5 text-xs text-ink-muted">
          <Clock className="size-3.5" aria-hidden /> Works once · expires {expiry(invitation.expiresAt)}
        </p>
        <Button type="button" onClick={onClose}>
          Done
        </Button>
      </div>
    </div>
  );
}

/**
 * A centred dialog over a dimmed page. Escape and the backdrop both close it,
 * and focus goes into it on open so a keyboard user lands on the content.
 */
export function Modal({ open, onClose, children }: { open: boolean; onClose: () => void; children: ReactNode }) {
  const panel = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && onClose();
    document.addEventListener("keydown", onKey);
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    panel.current?.focus();
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = previous;
    };
  }, [open, onClose]);

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center p-3 sm:items-center sm:p-6">
      <div
        className="absolute inset-0 bg-[rgb(11_42_32/0.55)] backdrop-blur-[2px] animate-in fade-in"
        onClick={onClose}
        aria-hidden
      />
      <div
        ref={panel}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
        className="relative max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-card border border-line bg-card p-5 shadow-overlay outline-none animate-in fade-in zoom-in-95 sm:p-6"
      >
        {children}
      </div>
    </div>
  );
}
